kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: JoinConfiguration
  nodeRegistration:
    criSocket: "/var/run/crio/crio.sock"
- |
  kind: InitConfiguration
  nodeRegistration:
    criSocket: "/var/run/crio/crio.sock"
nodes:
- role: control-plane
  image: localhost/vrutkovs/kindest-node-crio:v1.17.2
- role: worker
  image: localhost/vrutkovs/kindest-node-crio:v1.17.2
- role: worker
  image: localhost/vrutkovs/kindest-node-crio:v1.17.2
